spring:
  application:
    name: "cards" # tell ms to look for config files starting with "accounts"
  profiles:
    active: prod
  config:
    # "configserver" is used no matter what your config server name is or its repo name
    import: "optional:configserver:http://localhost:8071"